'use strict';

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      try {
        await self.registration.unregister();
      } catch (e) {
        console.warn('Failed to unregister the service worker:', e);
      }

      try {
        const clients = await self.clients.matchAll({
          type: 'window',
        });
        // Reload clients to ensure they are not using the old service worker.
        clients.forEach((client) => {
          if (client.url && 'navigate' in client) {
            client.navigate(client.url);
          }
        });
      } catch (e) {
        console.warn('Failed to navigate some service worker clients:', e);
      }
    })()
  );
});
// This file is merged into the Flutter service worker to handle push notifications.
// It is automatically generated by the merge_sw.sh script.
self.addEventListener("push", function (event) {
  if (!event.data) {
    console.log("[push-sw] No data in push event");
    return;
  }

  const text = event.data.text();

  console.log(text);

  const baseHref = self.location.pathname.split('/').slice(0, -1).join('/') + '/';
  console.log("[push-sw] Base Href:", baseHref);
  const iconPath = `${baseHref}icons/Icon-192.png`;

  const title = "Agenda";
  const options = {
    body: text || "Check your task list.",
    icon: iconPath,
    badge: iconPath,
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});
