#!/bin/bash
set -e

PUSH_SW="./web/push-sw.js"
FLUTTER_SW="./build/web/flutter_service_worker.js"

if [[ ! -f "$PUSH_SW" ]]; then
  echo "❌ push-sw.js not found!"
  exit 1
fi

if [[ ! -f "$FLUTTER_SW" ]]; then
  echo "❌ flutter_service_worker.js not found!"
  # create an empty file if it doesn't exist
  echo "// This file is automatically generated. Do not edit." > "$FLUTTER_SW"
  echo "✅ Created empty flutter_service_worker.js"
fi

echo "🔧 Merging push-sw.js into flutter_service_worker.js"
cat "$PUSH_SW" >> "$FLUTTER_SW"
echo "✅ Merge complete"
