@echo off
setlocal

set "PUSH_SW=.\web\push-sw.js"
set "FLUTTER_SW=.\build\web\flutter_service_worker.js"

if not exist "%PUSH_SW%" (
    echo ❌ push-sw.js not found!
    exit /b 1
)

if not exist "%FLUTTER_SW%" (
    echo ❌ flutter_service_worker.js not found!
    rem create an empty file if it doesn't exist
    echo // This file is automatically generated. Do not edit. > "%FLUTTER_SW%"
    echo ✅ Created empty flutter_service_worker.js
)

echo 🔧 Merging push-sw.js into flutter_service_worker.js
type "%PUSH_SW%" >> "%FLUTTER_SW%"
echo ✅ Merge complete

endlocal